[tool.poetry]
name = "pygrammalecte"
version = "0.1.0"
description = "Grammalecte, le correcteur grammatical en Python"
authors = ["Vincent Poulailleau <vpoulailleau@gmail.com>"]
license = "BSD-3-Clause"

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.20.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.1"
pytest-cov = "^2.10.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
